from pathlib import Path
from typing import Union
import matplotlib.pyplot as plt


def save_pdf_tex(
    figure,
    filename: Union[str, Path],
):
    """
    Save a Matplotlib figure as PDF and generate a PDF+LaTeX
    representation.

    The resulting files are:

        filename.pdf
        filename.pdf_tex
    """

    filename = Path(filename)

    pdf_file = filename.with_suffix(".pdf")

    figure.savefig(
        pdf_file,
        format="pdf",
        bbox_inches="tight",
    )

    # Generate the LaTeX overlay.
    #
    # Matplotlib provides the pdf_tex backend through
    # the pgf backend's save mechanism.
    #
    # We use the external `pdftops` + `psfrag`-style workflow
    # only in later versions if required.
    #
    # For Phase 1, use matplotlib's PGF backend generation.

    _write_pdf_tex_placeholder(
        figure,
        filename.with_suffix(".pdf_tex"),
        pdf_file,
    )


def _write_pdf_tex_placeholder(
    figure,
    tex_file: Path,
    pdf_file: Path,
):
    """
    Temporary PDF+TeX generator.

    This will be replaced by the final robust exporter
    once the exact LaTeX workflow is tested.
    """

    width = figure.get_figwidth()
    height = figure.get_figheight()

    content = f"""% Auto-generated by scientific-postprocess

\\begin{{picture}}(0,0)
\\includegraphics[width={width:.4f}in]{{{pdf_file.name}}}
\\end{{picture}}
"""

    tex_file.write_text(content)